# Generated by Django 2.0.5 on 2019-01-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllink',
            name='website',
            field=models.TextField(),
        ),
    ]
